#!/bin/bash

set -e

function usage() {
  cat << EOF
Usage:
  git root

Description:
  Outputs the root directory of the git repository.
EOF
}

if [ $# -ne 0 ]; then
  usage
  exit 1
fi

git rev-parse --show-toplevel