#!/bin/bash

set -e

function usage() {
  cat <<EOF
Usage:
  git fetchout <branch>

Description:
  Fetches the branch from the remote repository and checks it out.
EOF
}

if [ $# -ne 1 ]; then
  usage
  exit 1
fi

branch=$1
git fetch origin "$branch"
git checkout "$branch"
