#!/bin/bash

set -e

function usage() {
  cat <<EOF
Usage:
  git default [options]

Description:
  Outputs the default branch of the git repository.

Options:
  -r, --remote   Show the default branch of the remote repository
                 If not specified, show the default branch of the local repository
  -h, help       Show this help message
EOF
}

should_fetch_remote=false

while [[ $# -gt 0 ]]; do
  case $1 in
  -r | --remote)
    should_fetch_remote=true
    shift
    ;;
  -h | help)
    usage
    exit 0
    ;;
  *)
    echo "Unknown option: $1"
    usage
    exit 1
    ;;
  esac
done

if [[ "$should_fetch_remote" = true ]]; then
  git remote show origin | grep 'HEAD branch' | awk '{print $NF}'
else
  git symbolic-ref --short HEAD
fi
